---
- name: Configure the client to use the rsyncd transport method
  ansible.builtin.import_tasks: client-rsyncd.yml
  when: backuppc_client_xfer_method == "rsyncd"

- name: Configure the client to use the rsyncd transport method
  ansible.builtin.import_tasks: client-rsync.yml
  when: backuppc_client_xfer_method == "rsync"
