---
- name: Configure Rsync
  ansible.builtin.template:
    src: rsyncd.conf.j2
    dest: /etc/rsyncd.conf
    owner: root
    group: root
    mode: '0600'
  notify: Restart Rsync

- name: Configure Rsync Secrets file
  ansible.builtin.template:
    src: rsyncd.secrets.j2
    dest: /etc/rsyncd.secrets
    owner: root
    group: root
    mode: '0600'
  notify: Restart Rsync
