---
- name: Install requirements
  ansible.builtin.import_tasks: install.yml

- name: Configure the client
  ansible.builtin.import_tasks: client.yml

- name: Configure the BackupPC server
  ansible.builtin.import_tasks: server.yml
