---
- name: Restart Rsync
  service:
    name: rsync
    state: restarted

- name: Restart Rsync
  service:
    name: rsync
    state: restarted

- name: Reload BackupPC on server
  service:
    name: backuppc
    state: reloaded
  delegate_to: "{{ backuppc_server_inventory_hostname }}"
  become: true
  run_once: true
